function(load_env_file filename)
  file(STRINGS ${filename} env_vars)
  foreach(line ${env_vars})
    string(REGEX MATCH "^([^=]+)=(.*)$" matched ${line})
    if(matched)
      set(${CMAKE_MATCH_1} "${CMAKE_MATCH_2}" PARENT_SCOPE)
    endif()
  endforeach()
endfunction()

function(check_env_file_changed ENV_FILE CHANGED_VAR)
  if(NOT EXISTS ${ENV_FILE})
    set(${CHANGED_VAR} TRUE PARENT_SCOPE)
    return()
  endif()

  file(TIMESTAMP ${ENV_FILE} CURRENT_TIMESTAMP)
  set(TIMESTAMP_FILE "${CMAKE_CURRENT_BINARY_DIR}/env_timestamp.txt")

  if(EXISTS ${TIMESTAMP_FILE})
    file(READ ${TIMESTAMP_FILE} PREVIOUS_TIMESTAMP)
    if(NOT "${PREVIOUS_TIMESTAMP}" STREQUAL "${CURRENT_TIMESTAMP}")
      set(${CHANGED_VAR} TRUE PARENT_SCOPE)
    else()
      set(${CHANGED_VAR} FALSE PARENT_SCOPE)
    endif()
  else()
    set(${CHANGED_VAR} TRUE PARENT_SCOPE)
  endif()

  file(WRITE ${TIMESTAMP_FILE} ${CURRENT_TIMESTAMP})
endfunction()